server:
  port: 8001
  
spring:
   datasource:
          url: jdbc:mysql://localhost:3306/ms
          username: root
          password: Lufa@7917
          driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      properties:
            hibernate :
                dialect:org.hibernate.dialect.MySQL8Dialect
      hibernate:
            ddl-auto: update
   application:
           name: CITIZEN-SERVICE